sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password:
  alioss:
    endpoint:  https://oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t87PUnVCZokfGWx9d8o
    access-key-secret: E7xKvU4VFeeeL99WMezd2hngaaAZAY
    bucket-name: springbootweb-sky-take-out
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wx5a7ab33dcc6a0c95
    secret: be5f33f0643d68fb0231ce8dbbcf4157
#    mchid: 1561414331
#    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
#    privateKeyFilePath: C:\software\apiclient_key.pem
#    apiV3Key: CZBK51236435wxpay435434323FFDuv3
#    weChatPayCertFilePat: C:\software\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://421362fc.r3.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://421362fc.r3.cpolar.top/notify/refundSuccess


